config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'vehicles#index'
  resources :categories
  resources :vehicles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :vehicles
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :category
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:modelo, :chassi, :preco, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="card-footer3">
    <%= f.button :submit , class: "card-footer3 submit"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<div class="card-footer">
<h1>Editing Category</h1>

<div class="card-footer">
<%= render 'form', category: @category %>
<div>
<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
<div>
<div>

app/views/categories/index.html.erb
<div class="container">
<div class="card-footer">
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
<%=link_to "sair da sessão",destroy_user_session_path,method: :delete%>
<%= link_to 'veiculos', "/vehicles" %>
<%= link_to "Editar usuario", edit_user_registration_path %>

<div>
<div>

app/views/categories/new.html.erb
<div class="container">


<div class="card-footer">
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

<div>
<div>

app/views/categories/show.html.erb
<div class="container">
<div class="card-footer">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<div>
<div>

app/views/layouts/_flashmessages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :modelo %>
    <%= f.input :chassi %>
    <%= f.input :preco %>
    <%= f.association :category, prompt:'escolha o veiculo' %>
  </div>

  <div class="card-footer3">
    <%= f.button :submit , class: "card-footer3 submit"%>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="container">
<div class="card-footer">
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>
<div>
<div>

app/views/vehicles/index.html.erb
<div class="container">



<div class="card-footer">
<p id="notice"><%= notice %></p>
<h2>Veículos</h2>

<table>

  <thead>
  
    <tr>
    
      <th>Modelo</th>
      <th>Chassi</th>
      <th>Preco</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    
    <% @vehicles.each do |vehicle| %>
      
      <tr>
      
        <td><%= vehicle.modelo %></td>
        <td><%= vehicle.chassi %></td>
        <td><%= vehicle.preco %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<%= link_to 'adicionar veiculo', new_vehicle_path %>
<%=link_to "sair da sessão",destroy_user_session_path,method: :delete%>
<%= link_to 'categorias', "/categories" %>
<%= link_to "Editar usuario", edit_user_registration_path %>
<div>
<div>

app/views/vehicles/new.html.erb
<div class="container">


<div class="card-footer">
<h1>New Vehicle</h1>
<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>
<div>
<div>

app/views/vehicles/show.html.erb
<div class="container">
<div class="card-footer5">
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @vehicle.modelo %>
</p>

<p>
  <strong>Chassi:</strong>
  <%= @vehicle.chassi %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @vehicle.preco %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
<div>
<div>